const express = require("express");
const router = express.Router();
const authMiddleware = require("../middleware/auth.middleware");
const roleMiddleware = require("../middleware/role.middleware");
const ROLES = require("../constants/roles");
const base = require("../controllers/host.controller");
const management = require("../controllers/hostBooking.controller");

router.use(authMiddleware);
router.use(roleMiddleware(ROLES.HOST));
router.get("/dashboard", base.getDashboardStats);
router.get("/apartments", base.getMyApartments);
router.get("/apartments/pending", base.getPendingApartments);
router.get("/apartments/approved", base.getApprovedApartments);
router.get("/apartments/rejected", base.getRejectedApartments);
router.get("/apartments/inactive", base.getInactiveApartments);
router.get("/apartments/suspended", base.getSuspendedApartments);
router.get("/bookings", management.getHostBookings);
router.get("/bookings/:id", management.getHostBookingDetails);
router.patch("/bookings/:id/status", management.updateBookingStatus);
router.get("/availability", management.getAvailability);
router.get("/revenue", management.getRevenue);
router.get("/notification-snapshot", management.getHostNotificationSnapshot);
module.exports = router;
