import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Link, useParams } from "react-router-dom";
import toast from "react-hot-toast";
import hostService from "../../services/host.service";
const d = (v) => new Date(v).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
const purposeLabel = (value) => ({ leisure: "Leisure or vacation", business: "Business or work", family_visit: "Family or personal visit", other: "Other purpose" })[value] || "Not specified";
export default function HostBookingDetails() {
  const { id } = useParams(); const [booking, setBooking] = useState(null);
  useEffect(() => { hostService.getBookingDetails(id).then((r) => setBooking(r.data)).catch((e) => toast.error(e.response?.data?.message || "Booking not found")); }, [id]);
  if (!booking) return <div className="min-h-screen bg-slate-50 p-10"><div className="mx-auto h-96 max-w-5xl animate-pulse rounded-3xl bg-white"/></div>;
  return <div className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-5xl space-y-6"><Link to="/host/bookings" className="text-sm font-black text-[#FF385C]">← Back to bookings</Link><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="overflow-hidden rounded-[30px] bg-white shadow-xl"><img src={booking.apartment?.images?.[0]?.url || booking.apartment?.images?.[0]} className="h-64 w-full object-cover"/><div className="grid gap-8 p-7 lg:grid-cols-[1.3fr_.7fr]"><section><p className="text-xs font-black uppercase tracking-widest text-[#FF385C]">Booking #{booking._id.slice(-7).toUpperCase()}</p><h1 className="mt-2 text-3xl font-black">{booking.apartment?.title}</h1><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info label="Check-in" value={d(booking.checkIn)}/><Info label="Check-out" value={d(booking.checkOut)}/><Info label="Guests" value={`${booking.guestsCount} guests`}/><Info label="Payment" value={booking.paymentStatus}/></div><h2 className="mt-8 text-lg font-black">Timeline</h2><div className="mt-4 space-y-4 border-l-2 border-rose-100 pl-5">{booking.history?.map((h)=><div key={h._id}><p className="font-black">{h.title}</p><p className="text-sm text-slate-500">{h.description}</p><p className="mt-1 text-xs text-slate-400">{d(h.changedAt)}</p></div>)}</div></section><aside className="h-fit rounded-3xl bg-slate-950 p-6 text-white"><div className="flex items-center gap-3"><img src={booking.guest?.avatar || "https://placehold.co/80"} className="h-14 w-14 rounded-2xl object-cover"/><div><p className="text-xs text-slate-400">Guest</p><h2 className="font-black">{booking.guest?.name}</h2></div></div><div className="mt-6 space-y-3 text-sm"><p>✉️ {booking.guest?.email}</p><p>📞 {booking.guest?.phone || "Not provided"}</p><p>🎯 {purposeLabel(booking.purpose?.category)}</p><p>📝 {booking.purpose?.details || "No additional purpose details"}</p><p>💬 {booking.message || "No booking note"}</p></div><div className="mt-6 rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-400">Total amount</p><p className="text-2xl font-black">₹{Number(booking.pricing?.totalAmount || 0).toLocaleString("en-IN")}</p></div></aside></div></motion.div></div></div>;
}
function Info({label,value}){return <div className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 font-black capitalize text-slate-800">{value}</p></div>}


