const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const morgan = require("morgan");
const authRoutes = require("./routes/auth.routes");
const apartmentRoutes = require("./routes/apartment.routes");
const ownerRoutes = require("./routes/owner.routes");
const hostRoutes = require("./routes/host.routes");
const bookingRoutes = require("./routes/booking.routes");
const paymentRoutes = require("./routes/payment.routes");
const wishlistRoutes = require("./routes/wishlist.routes");
const reviewRoutes = require("./routes/review.routes");
const subscriptionRoutes = require("./routes/subscription.routes");
const notificationRoutes = require("./routes/notification.routes");
const chatRoutes = require("./routes/chat.routes");
const guestRoutes = require("./routes/guest.routes");
const supportRoutes = require("./routes/support.routes");
const errorHandler = require("./middleware/error.middleware");
const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || true, credentials: true }));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(helmet());
app.use(morgan("dev"));
app.get("/", (req, res) => res.status(200).json({ success: true, message: "StayNest API Running 🚀" }));
app.use("/api/auth", authRoutes);
app.use("/api/apartments", apartmentRoutes);
app.use("/api/owner", ownerRoutes);
app.use("/api/host", hostRoutes);
app.use("/api/bookings", bookingRoutes);
app.use("/api/payments", paymentRoutes);
app.use("/api/subscriptions", subscriptionRoutes);
app.use("/api/notifications", notificationRoutes);
app.use("/api/chat", chatRoutes);
app.use("/api/guest", guestRoutes);
app.use("/api/support", supportRoutes);
app.use("/api/wishlist", wishlistRoutes);
app.use("/api/reviews", reviewRoutes);
app.use((req, res) => res.status(404).json({ success: false, message: "Route Not Found" }));
app.use(errorHandler);
module.exports = app;