import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";
import loyaltyService from "../../services/loyalty.service";
import GuestPageHeader from "../../components/guest/GuestPageHeader";

const date = (value) => new Date(value).toLocaleString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

export default function LoyaltyRewards() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; (async () => { try { const response = await loyaltyService.getMyLoyalty(); if (active) setData(response.data); } catch (requestError) { if (active) setError(requestError.response?.data?.message || "Loyalty wallet load nahi hua."); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, []);
  if (loading) return <div className="grid min-h-[70vh] place-items-center"><div className="h-11 w-11 animate-spin rounded-full border-4 border-[#FF385C] border-t-transparent" /></div>;
  const account = data?.account || {};
  return <div className="min-h-screen bg-gradient-to-b from-amber-50/70 via-white to-slate-50 px-4 py-7 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><GuestPageHeader eyebrow="Loyalty Rewards" title="Your StayNest points wallet" description="Successful bookings par points earn karein aur next booking me redeem karein." />{error && <div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}<motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="mt-6 overflow-hidden rounded-[32px] bg-gradient-to-br from-amber-400 via-orange-500 to-[#FF385C] p-7 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-white/70">Available balance</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><p className="text-5xl font-black">{account.balance || 0}</p><p className="mt-1 text-sm font-bold text-white/75">loyalty points</p></div><span className="rounded-full bg-white/20 px-4 py-2 text-sm font-black capitalize backdrop-blur">{account.tier || "explorer"} tier</span></div></motion.section><section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Lifetime earned",account.lifetimeEarned || 0,"🎁"],["Redeemed",account.lifetimeRedeemed || 0,"💸"],["Reversed",account.lifetimeReversed || 0,"↩️"],["Value",`₹${Math.floor((account.balance || 0)/(data?.config?.POINTS_PER_RUPEE_DISCOUNT || 10))}`,"₹"]].map(([label,value,icon],index)=><motion.div key={label} initial={{ opacity:0,y:12 }} animate={{ opacity:1,y:0 }} transition={{delay:index*.04}} className="rounded-[24px] border border-amber-100 bg-white p-5 shadow-sm"><span className="text-2xl">{icon}</span><p className="mt-3 text-2xl font-black">{value}</p><p className="text-xs font-bold text-slate-400">{label}</p></motion.div>)}</section><section className="mt-6 overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="text-xl font-black">Points history</h2><p className="mt-1 text-xs text-slate-400">Credits and redemptions ka complete ledger.</p></div><div className="divide-y divide-slate-100">{(data?.transactions || []).map((item)=><div key={item._id} className="flex items-center justify-between gap-4 p-5"><div><p className="font-black capitalize text-slate-800">{item.type.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-slate-400">{item.description}</p><p className="mt-1 text-[10px] font-bold text-slate-400">{date(item.createdAt)}</p></div><div className="text-right"><p className={`text-lg font-black ${item.direction === "credit" ? "text-emerald-600" : "text-red-600"}`}>{item.direction === "credit" ? "+" : "-"}{item.points}</p><p className="text-[10px] font-bold text-slate-400">Balance {item.balanceAfter}</p></div></div>)}{!data?.transactions?.length && <div className="p-12 text-center text-sm font-semibold text-slate-400">No points transactions yet.</div>}</div></section></div></div>;
}