import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";
import paymentService from "../../services/payment.service";
import GuestPageHeader from "../../components/guest/GuestPageHeader";

const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN")}`;
const date = (value) => new Date(value).toLocaleString("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });

export default function PaymentHistory() {
  const [payments, setPayments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [downloading, setDownloading] = useState("");
  useEffect(() => { let active = true; (async () => { try { const response = await paymentService.getHistory(); if (active) setPayments(response.data || []); } catch (requestError) { if (active) setError(requestError.response?.data?.message || "Payment history load nahi hui."); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, []);
  const download = async (payment) => { try { setDownloading(payment._id); const result = await paymentService.downloadReceipt(payment._id); const url = URL.createObjectURL(result.blob); const link = document.createElement("a"); link.href = url; link.download = result.fileName; link.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(requestError.response?.data?.message || "Receipt download nahi hui."); } finally { setDownloading(""); } };
  return <div className="min-h-screen bg-slate-50 px-4 py-7 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><GuestPageHeader eyebrow="Payments" title="Payment history & receipts" description="Booking payment status track karein aur successful payments ki PDF receipt download karein." />{error && <div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{loading ? <div className="grid min-h-72 place-items-center"><div className="h-10 w-10 animate-spin rounded-full border-4 border-[#FF385C] border-t-transparent" /></div> : <div className="mt-6 space-y-4">{payments.map((payment,index)=><motion.article key={payment._id} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:index*.04}} className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-slate-900">{payment.booking?.apartment?.title || "Booking Payment"}</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${payment.status === "success" ? "bg-emerald-50 text-emerald-700" : payment.status === "failed" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{payment.status}</span></div><p className="mt-1 text-xs font-semibold text-slate-400">{date(payment.createdAt)} · {payment.razorpayPaymentId || payment.razorpayOrderId}</p></div><div className="flex items-center gap-3"><p className="text-xl font-black">{money(payment.amount)}</p>{payment.status === "success" && <button onClick={()=>download(payment)} disabled={downloading===payment._id} className="rounded-2xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white disabled:opacity-50">{downloading===payment._id ? "Preparing..." : "⬇ PDF Receipt"}</button>}</div></div></motion.article>)}{!payments.length && <div className="rounded-[28px] border border-dashed border-slate-300 bg-white py-20 text-center"><div className="text-5xl">💳</div><h2 className="mt-4 text-lg font-black">No payments yet</h2></div>}</div>}</div></div>;
}